Mobile menu made with Abdullah
Nedramrez/portfolio pull request #11
Opened 2022-06-14 15:11 UTC by Nedramrez

- Add a hidden mobile menu
- Add javascript code for mobile menu
- Ask to commit the coding partner

2022-06-14 17:11 UTC, youmari requested changes
Hi @Nedramrez , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great title and short summary
✔️ Github flow 
✔️ No linter error

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-14 17:11 UTC, youmari commented on index.html
> +              <a onclick="mobileMenu()" href="#contact">Contact</a>
- [x] please make sure that your navigation  links are clear and looks white as in the Figma design 
- Figma
![image](https://user-images.githubusercontent.com/61790587/173636406-a1f8bd35-f546-408e-89f1-92b8f9d5dd42.png)
- Yours
![image](https://user-images.githubusercontent.com/61790587/173636524-7c8a726b-3bd8-4dc8-a6ef-25f1ad561fbd.png)

2022-06-14 19:05 UTC, vechicin requested changes
# Hi @Nedramrez ✋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🚨 


 ## Highlights ⚡ 

- [x] Good job trying to implement the previous reviewer's requirements

 ## Required Changes ♻️

- [ ] I'm experiencing a slight horizontal scroll in both the mobile and desktop versions. This makes for bad UI/UX. Please fix it. I am using Google Chrome, for reference.

_Check the comments under the review._

## Optional suggestions 📂 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-14 19:05 UTC, vechicin commented on styles.css
> +}
While you did address the changes required by the previous reviewer, you didn't do so properly. Please take a closer look at the template design and make sure your design looks identical to it. Thinks to think about (but not exclusively): margins, padding, color, opacity, font, and font size.

Additionally, your mobile menu is not covering the screen vertically. That makes for bad UI/UX.

<img width="192" alt="Screen Shot 2022-06-14 at 14 03 24" src="https://user-images.githubusercontent.com/82426682/173668636-12590234-fdaa-42d2-bcf5-f3c4cd819313.png">

Please fix it.

2022-06-15 15:08 UTC, roshan-bajgain approved these changes
Hi @Nedramrez, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-15 15:25 UTC, merged

2022-06-21 08:21 UTC, tufoinnkuo10 reviewed
Hi @Nedramrez , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🔕 ⛔ 🔴 

You have submitted a project, that has already been reviewed. kindly create a new pull request with new changes and ask for a review again. 😄 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._