Details popup
Nedramrez/portfolio pull request #13
Opened 2022-06-16 16:13 UTC by Nedramrez

- Prepare the javascript code
- Add mobile version details popup window
- Add desktop version details popup window

2022-06-16 17:32 UTC, omarsalem7 requested changes
Hi @Nedramrez 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights
- Descriptive pull request ✔️
- No linter errors ✔️
- Descriptive commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-16 17:32 UTC, omarsalem7 commented on script.js
> +};
- [ ] Kindly consider making the projects section is created dynamically with the information from the projects array (all the HTML of the section is created when the page loads).
- [ ] Also consider modal popup data is populated with the data from the projects array.

2022-06-22 14:18 UTC, zieeco requested changes
Hi @Nedramrez,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions

- [ ] Please do try as much as possible to ensure your design doesn't have a horizontal scroll behavior to improve the user experience.

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-22 14:18 UTC, zieeco commented on script.js
> +
**[REQUIRED CHANGES]**

- [ ] Hey, great job with the implementation, however, there are some issues to be addressed. Please, kindly fix the following issues stated below:

- The project images don't show on mobile and desktop versions of your portfolio website but only show on the modal pop-up.
- The mobile version of the modal doesn't show all the content. The `see live` and `see source` buttons are not showing up.
- The desktop version of the modal doesn't match the Figma design:
- - The cancel button is not showing.
- - The image is not well aligned as that on the Figma design.
- - The `see live` and `see source` buttons are not showing up.


:point_right: **Please, kindly refer to the Figma design to fix the issue**

2022-06-22 15:02 UTC, Nedramrez commented on script.js
> +
Hi @zieeco !
Thank you for your professional and friendly review.
Please, help me to understand the required changes. 
I cloned my repository to a different folder to check again and see all project images, the cancel button of the modal, all buttons showing up etc.
I attached screenshots.
![Скриншот, уақыты 2022-06-22 20-56-19](https://user-images.githubusercontent.com/100216952/175063274-a1362862-ed04-41dd-985f-a3ff13ef6e96.png)

![Скриншот, уақыты 2022-06-22 20-54-14](https://user-images.githubusercontent.com/100216952/175063242-0ba87a5d-0965-47f4-a04f-275601622587.png)
![Скриншот, уақыты 2022-06-22 20-54-29](https://user-images.githubusercontent.com/100216952/175063250-21c54777-81e8-4ea5-b05d-a373ee9c0852.png)
![Скриншот, уақыты 2022-06-22 20-54-37](https://user-images.githubusercontent.com/100216952/175063255-6b36f05a-1240-4aba-bc65-53cc0bd1d0e4.png)
![Скриншот, уақыты 2022-06-22 20-54-58](https://user-images.githubusercontent.com/100216952/175063262-06a1fe6a-efe9-4f9f-b200-2287cb611d5e.png)

2022-06-22 15:04 UTC, Nedramrez commented on script.js
> +
And I asked my partner to clone. He shared his screen and he could see all images and buttons too.

2022-06-22 15:17 UTC, zieeco commented on script.js
> +
@Nedramrez, It shows well locally, but not online I mean, kindly change the github pages to that of this detailed pop branch so I check again.

2022-06-22 15:58 UTC, zieeco requested changes
Hi @Nedramrez,


Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- [ ] Please do try as much as possible to ensure your design doesn't have a horizontal scroll behavior to improve the user experience.


**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-22 15:58 UTC, zieeco commented on script.js
> +
**[REQUIRED CHANGES]**

- Hey, while every other change has been met, there's still an issue with the image in your pop up, see the video below and compare with the Figma design

*your pop p in action*

https://user-images.githubusercontent.com/59397159/175076569-6b507122-0862-4818-a63d-d05cef7d1e75.mp4

*figma design*
![figma__](https://user-images.githubusercontent.com/59397159/175076790-4ef041a2-42f7-4968-8f77-e1dca0a8db53.png)

2022-06-22 16:52 UTC, AmaduKamara approved these changes
# Status: Approved 🟢🟢🟢 

Hi @Nedramrez,

![YesYouAreGIF](https://user-images.githubusercontent.com/50941074/175093781-c453da0c-7220-41c1-b818-2f661422d686.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights

✅ Correct use of Gitflow
✅ No linter error

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-06-22 17:08 UTC, merged

2022-06-22 17:08 UTC, Nedramrez commented
Thank you very much!