Add the email validation code to a script.js file
Nedramrez/portfolio pull request #18
Opened 2022-06-23 10:03 UTC by Nedramrez

- Add the email validation code to a script.js file

2022-06-23 13:22 UTC, omarsalem7 requested changes
Hi @Nedramrez 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights
- Descriptive pull request ✔️
- No linter errors ✔️

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-23 13:22 UTC, omarsalem7 commented on script.js
> +    lowcaseError.innerHTML = 'Please use lowercase letters and proper mail pattern';
- [ ] Kindly consider showing an error message to the user near the submit button not between inputs fields.

2022-06-23 17:26 UTC, AmaduKamara approved these changes
# Status: Approved 🟢🟢🟢 

Hi @Nedramrez,

![YesYouAreGIF](https://user-images.githubusercontent.com/50941074/175358427-a1f06a0b-1ac6-468f-82bf-957d9625b5e7.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ Good commit messages 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-06-24 09:14 UTC, merged

2022-06-24 09:14 UTC, Nedramrez commented
Thank you very much!